### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by LittleHobbyShop** [properprinting/PPC#9]
Seems some dependencies are missing in source:
![image](https://user-images.githubusercontent.com/16748684/104911143-4c8f1c80-5982-11eb-8afe-4d8767d80c4b.png)

**Comment by properprinting** [comment]
Thanks for the feedback! These dependencies can be downloaded from here https://github.com/properprinting/MID and this must be placed in the instr.lib folder. I updated the readme file because this was not very clear.
